export const PLAYER_LIST_SELECT = [
  'id',
  'first_name',
  'last_name',
  'dni',
  'jersey_number',
  'birth_date',
  'category',
  'phone',
  'email',
  'address',
  'payment_status',
  'last_payment_date',
  'is_active',
  'photo_url',
  'photo_thumb_url',
  'created_at',
  'updated_at',
].join(', ');

export const PLAYER_DETAIL_SELECT = [
  'id',
  'first_name',
  'last_name',
  'dni',
  'jersey_number',
  'birth_date',
  'category',
  'phone',
  'email',
  'address',
  'user_id',
  'profile_id',
  'payment_status',
  'last_payment_date',
  'is_active',
  'photo_url',
  'photo_thumb_url',
  'notes',
  'created_at',
  'updated_at',
].join(', ');

export const PAYMENT_HISTORY_SELECT = [
  'id',
  'player_id',
  'amount',
  'payment_date',
  'method',
  'period',
  'status',
  'notes',
  'receipt_path',
  'receipt_file_name',
  'reviewed_at',
  'reviewed_by',
  'mp_payment_id',
  'mp_preference_id',
  'created_at',
].join(', ');
